version: '3.7'

services:
  
  
  wiki:
    build:
      context: ./services/backend-server
      dockerfile: Dockerfile
    entrypoint: ["/usr/src/app/entrypoint.sh"]
    volumes:
        - ./services/backend-server/:/usr/src/app/
    ports:
        - 8000:8000
    env_file:
      - ./services/backend-server/.env.dev
    depends_on: 
      - wiki-db

  wiki-db:
    image: postgres:12-alpine
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_USER=wiki
      - POSTGRES_PASSWORD=wiki
      - POSTGRES_DB=wiki_dev_db

volumes: 
  postgres_data: