
name: MusuemWiki CI/CD Workflow

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: cd into backend-server dir
        run: cd services/backend-server
      - name: Log into Github Container Registry, Pull & Build a docker image
        run: |
          docker login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.PAT }} 
          docker pull pull $IMAGE:latest
          docker build
            --cache-from $IMAGE:latest
            --tag $IMAGE:latest
            --file ./Dockerfile.prod
            "."
          docker push $IMAGE:latest
